name: Hourly News Fetch

on:
  workflow_dispatch: # Allows you to run the workflow manually
  schedule:
    # Runs at the top of every hour
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode and Create Service Account File
        run: echo "${{ secrets.GOOGLE_SHEETS_CREDENTIALS_JSON }}" | base64 --decode > ${{ github.workspace }}/service_account.json

      - name: Run News Pipeline Script
        env:
          NEWSDATA_API_KEY: ${{ secrets.NEWSDATA_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SPREADSHEET_NAME: ${{ secrets.SPREADSHEET_NAME }}
        run: python main.py
